=encoding utf-8

=head1 NAME

App::Greple::xlate - μονάδα υποστήριξης μετάφρασης για το greple

=head1 SYNOPSIS

    greple -Mxlate -e ENGINE --xlate pattern target-file

    greple -Mxlate::deepl --xlate pattern target-file

=head1 VERSION

Version 0.26

=head1 DESCRIPTION

B<Greple> Το μοντούλο B<xlate> εντοπίζει τα τμήματα κειμένου και τα αντικαθιστά με το μεταφρασμένο κείμενο. Περιλαμβάνει τα μοντούλα DeepL (F<deepl.pm>) και ChatGPT (F<gpt3.pm>) για τη μηχανή πίσω από το σύστημα.

Εάν θέλετε να μεταφράσετε ένα κανονικό τμήμα κειμένου σε έγγραφο στυλ L<pod>, χρησιμοποιήστε την εντολή B<greple> με τις μονάδες C<xlate::deepl> και C<perl> όπως εξής:

    greple -Mxlate::deepl -Mperl --pod --re '^(\w.*\n)+' --all foo.pm

Το πρότυπο C<^(\w.*\n)+> σημαίνει συνεχόμενες γραμμές που ξεκινούν με αλφαριθμητικό γράμμα. Αυτή η εντολή εμφανίζει την περιοχή που πρόκειται να μεταφραστεί. Η επιλογή B<--all> χρησιμοποιείται για να παράγει ολόκληρο το κείμενο.

=for html <p>
<img width="750" src="https://raw.githubusercontent.com/kaz-utashiro/App-Greple-xlate/main/images/select-area.png">
</p>

Στη συνέχεια, προσθέστε την επιλογή C<--xlate> για να μεταφράσετε την επιλεγμένη περιοχή. Θα την εντοπίσει και θα την αντικαταστήσει με την έξοδο της εντολής B<deepl>.

Από προεπιλογή, το αρχικό και το μεταφρασμένο κείμενο εκτυπώνονται στη μορφή "conflict marker" συμβατή με το L<git(1)>. Χρησιμοποιώντας τη μορφή C<ifdef>, μπορείτε να λάβετε το επιθυμητό τμήμα με την εντολή L<unifdef(1)> εύκολα. Η μορφή μπορεί να καθοριστεί με την επιλογή B<--xlate-format>.

=for html <p>
<img width="750" src="https://raw.githubusercontent.com/kaz-utashiro/App-Greple-xlate/main/images/format-conflict.png">
</p>

Εάν θέλετε να μεταφράσετε ολόκληρο το κείμενο, χρησιμοποιήστε την επιλογή B<--match-all>. Αυτό είναι ένας συντομευμένος τρόπος για να καθορίσετε ότι το πρότυπο ταιριάζει με ολόκληρο το κείμενο C<(?s).+>.

=head1 OPTIONS

=over 7

=item B<--xlate>

=item B<--xlate-color>

=item B<--xlate-fold>

=item B<--xlate-fold-width>=I<n> (Default: 70)

Καλέστε τη διαδικασία μετάφρασης για κάθε ταιριαστή περιοχή.

Χωρίς αυτήν την επιλογή, το B<greple> συμπεριφέρεται ως ένα κανονικό πρόγραμμα αναζήτησης. Έτσι μπορείτε να ελέγξετε ποιο μέρος του αρχείου θα υπόκειται στη μετάφραση πριν καλέσετε την πραγματική εργασία.

Το αποτέλεσμα της εντολής πηγαίνει στην τυπική έξοδο, οπότε αν χρειάζεται ανακατεύθυνση σε αρχείο, ή σκεφτείτε να χρησιμοποιήσετε το πρόσθετο L<App::Greple::update>.

Η επιλογή B<--xlate> καλεί την επιλογή B<--xlate-color> με την επιλογή B<--color=never>.

Με την επιλογή B<--xlate-fold>, το μεταφρασμένο κείμενο διπλώνεται με το καθορισμένο πλάτος. Το προεπιλεγμένο πλάτος είναι 70 και μπορεί να οριστεί με την επιλογή B<--xlate-fold-width>. Τέσσερεις στήλες είναι καταλεγμένες για τη λειτουργία run-in, οπότε κάθε γραμμή μπορεί να περιέχει το πολύ 74 χαρακτήρες.

=item B<--xlate-engine>=I<engine>

Καθορίζει τη μηχανή μετάφρασης που θα χρησιμοποιηθεί. Εάν καθορίσετε απευθείας το μοντούλο της μηχανής, όπως C<-Mxlate::deepl>, δεν χρειάζεται να χρησιμοποιήσετε αυτήν την επιλογή.

=item B<--xlate-labor>

=item B<--xlabor>

Αντί να καλέσετε τη μηχανή μετάφρασης, αναμένεται να εργαστείτε για αυτήν. Αφού προετοιμάσετε το κείμενο προς μετάφραση, αντιγράφονται στο πρόχειρο. Αναμένεται να τα επικολλήσετε στη φόρμα, να αντιγράψετε το αποτέλεσμα στο πρόχειρο και να πατήσετε Enter.

=item B<--xlate-to> (Default: C<EN-US>)

Καθορίστε τη γλώσσα προορισμού. Μπορείτε να λάβετε τις διαθέσιμες γλώσσες με την εντολή C<deepl languages> όταν χρησιμοποιείτε τη μηχανή B<DeepL>.

=item B<--xlate-format>=I<format> (Default: C<conflict>)

Καθορίστε τη μορφή εξόδου για το αρχικό και μεταφρασμένο κείμενο.

=over 4

=item B<conflict>, B<cm>

Εκτυπώστε το αρχικό και το μεταφρασμένο κείμενο σε μορφή συγκρουόμενου δείκτη L<git(1)>.

    <<<<<<< ORIGINAL
    original text
    =======
    translated Japanese text
    >>>>>>> JA

Μπορείτε να ανακτήσετε το αρχικό αρχείο με την επόμενη εντολή L<sed(1)>.

    sed -e '/^<<<<<<< /d' -e '/^=======$/,/^>>>>>>> /d'

=item B<ifdef>

Εκτυπώστε το αρχικό και το μεταφρασμένο κείμενο σε μορφή C<#ifdef> του L<cpp(1)>.

    #ifdef ORIGINAL
    original text
    #endif
    #ifdef JA
    translated Japanese text
    #endif

Μπορείτε να ανακτήσετε μόνο το ιαπωνικό κείμενο με την εντολή B<unifdef>:

    unifdef -UORIGINAL -DJA foo.ja.pm

=item B<space>

Εκτυπώστε το αρχικό και το μεταφρασμένο κείμενο χωρισμένα από μία κενή γραμμή.

=item B<xtxt>

Εάν η μορφή είναι C<xtxt> (μεταφρασμένο κείμενο) ή άγνωστη, εκτυπώνεται μόνο το μεταφρασμένο κείμενο.

=back

=item B<--xlate-maxlen>=I<chars> (Default: 0)

Καθορίστε το μέγιστο μήκος του κειμένου που θα αποσταλεί στο API κάθε φορά. Η προεπιλεγμένη τιμή έχει οριστεί για τη δωρεάν υπηρεσία λογαριασμού: 128Κ για το API (B<--xlate>) και 5000 για τη διεπαφή πρόχειρου (B<--xlate-labor>). Μπορείτε να αλλάξετε αυτές τις τιμές αν χρησιμοποιείτε την υπηρεσία Pro.

=item B<-->[B<no->]B<xlate-progress> (Default: True)

Δείτε το αποτέλεσμα της μετάφρασης σε πραγματικό χρόνο στην έξοδο STDERR.

=item B<--match-all>

Ορίστε ολόκληρο το κείμενο του αρχείου ως περιοχή στόχο.

=back

=head1 CACHE OPTIONS

Το πρόσθετο B<xlate> μπορεί να αποθηκεύει το μεταφρασμένο κείμενο για κάθε αρχείο και να το διαβάζει πριν από την εκτέλεση για να εξαλείψει τον χρόνο που απαιτείται για την επικοινωνία με τον διακομιστή. Με την προεπιλεγμένη στρατηγική προσωρινής αποθήκευσης C<auto>, διατηρεί τα δεδομένα προσωρινής αποθήκευσης μόνο όταν το αρχείο προσωρινής αποθήκευσης υπάρχει για το συγκεκριμένο αρχείο στόχο.

=over 7

=item --cache-clear

Η επιλογή B<--cache-clear> μπορεί να χρησιμοποιηθεί για την εκκίνηση της διαχείρισης της προσωρινής αποθήκευσης ή για την ανανέωση όλων των υπαρχόντων δεδομένων προσωρινής αποθήκευσης. Μόλις εκτελεστεί με αυτήν την επιλογή, θα δημιουργηθεί ένα νέο αρχείο προσωρινής αποθήκευσης αν δεν υπάρχει και στη συνέχεια θα διατηρείται αυτόματα.

=item --xlate-cache=I<strategy>

=over 4

=item C<auto> (Default)

Διατηρήστε το αρχείο προσωρινής αποθήκευσης αν υπάρχει.

=item C<create>

Δημιουργήστε ένα κενό αρχείο προσωρινής αποθήκευσης και τερματίστε.

=item C<always>, C<yes>, C<1>

Διατηρήστε την προσωρινή μνήμη ούτως ή άλλως, όσο το προορισμένο αρχείο είναι κανονικό αρχείο.

=item C<clear>

Καθαρίστε πρώτα τα δεδομένα της προσωρινής μνήμης.

=item C<never>, C<no>, C<0>

Ποτέ μην χρησιμοποιείτε το αρχείο της προσωρινής μνήμης, ακόμα κι αν υπάρχει.

=item C<accumulate>

Από προεπιλογή, τα αχρησιμοποίητα δεδομένα αφαιρούνται από το αρχείο της προσωρινής μνήμης. Εάν δεν θέλετε να τα αφαιρέσετε και να τα κρατήσετε στο αρχείο, χρησιμοποιήστε την επιλογή C<accumulate>.

=back

=back

=head1 COMMAND LINE INTERFACE

Μπορείτε εύκολα να χρησιμοποιήσετε αυτήν την ενότητα από τη γραμμή εντολών χρησιμοποιώντας την εντολή C<xlate> που περιλαμβάνεται στο αποθετήριο. Δείτε τις πληροφορίες βοήθειας της εντολής C<xlate> για τη χρήση.

=head1 EMACS

Φορτώστε το αρχείο F<xlate.el> που περιλαμβάνεται στο αποθετήριο για να χρησιμοποιήσετε την εντολή C<xlate> από τον επεξεργαστή Emacs. Η συνάρτηση C<xlate-region> μεταφράζει την δοθείσα περιοχή. Η προεπιλεγμένη γλώσσα είναι η C<EN-US> και μπορείτε να καθορίσετε τη γλώσσα καλώντας την με πρόθεμα.

=head1 ENVIRONMENT

=over 7

=item DEEPL_AUTH_KEY

Ορίστε το κλειδί πιστοποίησης σας για την υπηρεσία DeepL.

=item OPENAI_API_KEY

Κλειδί επαλήθευσης OpenAI.

=back

=head1 INSTALL

=head2 CPANMINUS

    $ cpanm App::Greple::xlate

=head2 TOOLS

Πρέπει να εγκαταστήσετε τα εργαλεία γραμμής εντολών για το DeepL και το ChatGPT.

L<https://github.com/DeepLcom/deepl-python>

L<https://github.com/tecolicom/App-gpty>

=head1 SEE ALSO

L<App::Greple::xlate>

L<App::Greple::xlate::deepl>

L<App::Greple::xlate::gpt3>

=over 7

=item L<https://github.com/DeepLcom/deepl-python>

Βιβλιοθήκη DeepL Python και εντολή CLI.

=item L<https://github.com/openai/openai-python>

Βιβλιοθήκη Python της OpenAI

=item L<https://github.com/tecolicom/App-gpty>

Διεπαφή γραμμής εντολών της OpenAI

=item L<App::Greple>

Δείτε το εγχειρίδιο B<greple> για λεπτομέρειες σχετικά με το πρότυπο κειμένου προορισμού. Χρησιμοποιήστε τις επιλογές B<--inside>, B<--outside>, B<--include>, B<--exclude> για να περιορίσετε την περιοχή της αντιστοίχισης.

=item L<App::Greple::update>

Μπορείτε να χρησιμοποιήσετε τον μονάδα C<-Mupdate> για να τροποποιήσετε αρχεία με βάση το αποτέλεσμα της εντολής B<greple>.

=item L<App::sdif>

Χρησιμοποιήστε το B<sdif> για να εμφανίσετε τη μορφή του δείκτη σύγκρουσης δίπλα-δίπλα με την επιλογή B<-V>.

=back

=head1 AUTHOR

Kazumasa Utashiro

=head1 LICENSE

Copyright © 2023 Kazumasa Utashiro.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
