=encoding utf-8

=head1 NAME

App::Greple::xlate - модуль підтримки перекладу для greple

=head1 SYNOPSIS

    greple -Mxlate -e ENGINE --xlate pattern target-file

    greple -Mxlate::deepl --xlate pattern target-file

=head1 VERSION

Version 0.28

=head1 DESCRIPTION

B<Greple> Модуль B<xlate> знаходить текстові блоки і замінює їх перекладеним текстом. В даний час в якості двигуна використовуються модулі DeepL (F<deepl.pm>) та ChatGPT (F<gpt3.pm>).

Якщо ви хочете перекласти звичайні текстові блоки, написані у стилі L<pod>, використовуйте команду B<greple> з модулем C<xlate::deepl> та C<perl> таким чином:

    greple -Mxlate::deepl -Mperl --pod --re '^(\w.*\n)+' --all foo.pm

Шаблон C<^(\w.*\n)+> означає послідовні рядки, що починаються з букви або цифри. Ця команда показує область, яку потрібно перекласти. Опція B<--all> використовується для виведення всього тексту.

=for html <p>
<img width="750" src="https://raw.githubusercontent.com/kaz-utashiro/App-Greple-xlate/main/images/select-area.png">
</p>

Потім додайте опцію C<--xlate>, щоб перекласти вибрану область. Вона знайде та замінить їх виводом команди B<deepl>.

За замовчуванням оригінальний та перекладений текст виводяться у форматі "конфліктного маркера", сумісного з L<git(1)>. Використовуючи формат C<ifdef>, ви можете легко отримати бажану частину за допомогою команди L<unifdef(1)>. Формат виводу можна вказати за допомогою опції B<--xlate-format>.

=for html <p>
<img width="750" src="https://raw.githubusercontent.com/kaz-utashiro/App-Greple-xlate/main/images/format-conflict.png">
</p>

Якщо ви хочете перекласти весь текст, використовуйте опцію B<--match-all>. Це скорочення для вказання шаблону C<(?s).+>, який відповідає всьому тексту.

=head1 OPTIONS

=over 7

=item B<--xlate>

=item B<--xlate-color>

=item B<--xlate-fold>

=item B<--xlate-fold-width>=I<n> (Default: 70)

Викликайте процес перекладу для кожної знайденої області.

Без цієї опції B<greple> працює як звичайна команда пошуку. Тому ви можете перевірити, яка частина файлу буде підлягати перекладу, перед викликом фактичної роботи.

Результат команди виводиться на стандартний вивід, тому перенаправте його до файлу, якщо потрібно, або розгляньте використання модуля L<App::Greple::update>.

Опція B<--xlate> викликає опцію B<--xlate-color> з опцією B<--color=never>.

З опцією B<--xlate-fold> перетворений текст складається за вказаною шириною. За замовчуванням ширина становить 70 і може бути встановлена за допомогою опції B<--xlate-fold-width>. Чотири стовпці зарезервовані для роботи з рядками, тому кожен рядок може містити максимум 74 символи.

=item B<--xlate-engine>=I<engine>

Вказує двигун перекладу, який буде використовуватися. Якщо ви вказуєте модуль двигуна безпосередньо, наприклад C<-Mxlate::deepl>, вам не потрібно використовувати цю опцію.

=item B<--xlate-labor>

=item B<--xlabor>

Замість виклику двигуна перекладу, очікується, що ви будете працювати з текстом, який потрібно перекласти. Після підготовки тексту для перекладу, вони копіюються в буфер обміну. Очікується, що ви вставите їх у форму, скопіюєте результат в буфер обміну та натиснете Enter.

=item B<--xlate-to> (Default: C<EN-US>)

Вкажіть цільову мову. Ви можете отримати доступні мови за допомогою команди C<deepl languages>, коли використовуєте двигун B<DeepL>.

=item B<--xlate-format>=I<format> (Default: C<conflict>)

Вкажіть формат виведення для оригінального та перекладеного тексту.

=over 4

=item B<conflict>, B<cm>

Вивести оригінальний та перекладений текст у форматі конфліктних маркерів L<git(1)>.

    <<<<<<< ORIGINAL
    original text
    =======
    translated Japanese text
    >>>>>>> JA

Ви можете відновити оригінальний файл за допомогою наступної команди L<sed(1)>.

    sed -e '/^<<<<<<< /d' -e '/^=======$/,/^>>>>>>> /d'

=item B<ifdef>

Вивести оригінальний та перекладений текст у форматі L<cpp(1)> C<#ifdef>.

    #ifdef ORIGINAL
    original text
    #endif
    #ifdef JA
    translated Japanese text
    #endif

Ви можете отримати лише японський текст за допомогою команди B<unifdef>:

    unifdef -UORIGINAL -DJA foo.ja.pm

=item B<space>

Вивести оригінальний та перекладений текст, розділені одним порожнім рядком.

=item B<xtxt>

Якщо формат - це C<xtxt> (перекладений текст) або невідомий, виводиться лише перекладений текст.

=back

=item B<--xlate-maxlen>=I<chars> (Default: 0)

Перекладіть наступний текст українською мовою, рядок за рядком.

=item B<-->[B<no->]B<xlate-progress> (Default: True)

Перекладіть наступний текст на українську мову.

=item B<--match-all>

Переглядайте результат перекладу в режимі реального часу у виводі STDERR.

=back

=head1 CACHE OPTIONS

Встановіть весь текст файлу як цільову область.

=over 7

=item --cache-clear

Модуль B<xlate> може зберігати кешований текст перекладу для кожного файлу та читати його перед виконанням, щоб уникнути надмірного запиту до сервера. За замовчуванням стратегія кешу C<auto> підтримує кешові дані тільки тоді, коли файл кешу існує для цільового файлу.

=item --xlate-cache=I<strategy>

=over 4

=item C<auto> (Default)

Опція B<--cache-clear> може бути використана для ініціювання керування кешем або оновлення всіх існуючих даних кешу. Після виконання з цією опцією буде створено новий файл кешу, якщо він не існує, і потім автоматично підтримуватиметься.

=item C<create>

Підтримуйте файл кешу, якщо він існує.

=item C<always>, C<yes>, C<1>

Створіть порожній файл кешу та вийдіть.

=item C<clear>

Підтримуйте кеш незалежно від того, чи є цільовий файл звичайним файлом.

=item C<never>, C<no>, C<0>

Спочатку очистіть дані кешу.

=item C<accumulate>

Ніколи не використовуйте файл кешу, навіть якщо він існує.

=back

=back

=head1 COMMAND LINE INTERFACE

За замовчуванням невикористані дані видаляються з файлу кешу. Якщо ви не хочете їх видаляти і зберігати в файлі, використовуйте C<accumulate>.

=head1 EMACS

Ви можете легко використовувати цей модуль з командного рядка, використовуючи команду C<xlate>, яка входить до репозиторію. Для використання команди C<xlate> з редактора Emacs завантажте файл F<xlate.el>, який входить до репозиторію. Функція C<xlate-region> перекладає задану область. Мова за замовчуванням - C<EN-US>, і ви можете вказати мову, викликаючи її з аргументом префіксу.

=head1 ENVIRONMENT

=over 7

=item DEEPL_AUTH_KEY

Встановіть свій ключ аутентифікації для сервісу DeepL.

=item OPENAI_API_KEY

Ключ аутентифікації OpenAI.

=back

=head1 INSTALL

=head2 CPANMINUS

    $ cpanm App::Greple::xlate

=head2 TOOLS

Вам потрібно встановити інструменти командного рядка для DeepL та ChatGPT.

L<https://github.com/DeepLcom/deepl-python>

L<https://github.com/tecolicom/App-gpty>

=head1 SEE ALSO

L<App::Greple::xlate>

L<App::Greple::xlate::deepl>

L<App::Greple::xlate::gpt3>

=over 7

=item L<https://github.com/DeepLcom/deepl-python>

Бібліотека DeepL для Python та командний рядок.

=item L<https://github.com/openai/openai-python>

Бібліотека OpenAI для Python

=item L<https://github.com/tecolicom/App-gpty>

Інтерфейс командного рядка OpenAI

=item L<App::Greple>

Докладніше про шаблон тексту цільового тексту див. у посібнику B<greple>. Використовуйте опції B<--inside>, B<--outside>, B<--include>, B<--exclude>, щоб обмежити область відповідності.

=item L<App::Greple::update>

Ви можете використовувати модуль C<-Mupdate>, щоб змінювати файли за результатами команди B<greple>.

=item L<App::sdif>

Використовуйте B<sdif>, щоб показати формат маркера конфлікту поруч з опцією B<-V>.

=back

=head1 AUTHOR

Kazumasa Utashiro

=head1 LICENSE

Copyright © 2023 Kazumasa Utashiro.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
